import assert from 'node:assert/strict';
import * as THREE from 'three';
import { MapGenerator } from '../src/mechanics/MapGenerator.js';

const generator = new MapGenerator(new THREE.Scene());
generator.springPunchItemsEnabled = true;
generator.springPunchCellBlocked = () => false;
generator.initMap();
assert.ok(generator.springPunchItems.size >= 2 && generator.springPunchItems.size <= 3, 'enabled spring punch must naturally spawn as a horizontal row of 2–3 boxes');
const initialItems = [...generator.springPunchItems.values()];
const first = initialItems[0];
assert.ok(initialItems.every((item) => item.z === first.z), 'ordinary party boxes must share one horizontal Z row');
assert.equal(new Set(initialItems.map((item) => item.x)).size, initialItems.length, 'horizontal party boxes need distinct X cells');
assert.ok(first.z >= 8, 'spring punch must stay beyond the initial z0-7 safety area');
assert.ok(generator.collectSpringPunchItemAt(first), 'spawned item must be collectible');
assert.equal(generator.springPunchItems.size, initialItems.length - 1, 'collecting one box leaves its horizontal siblings available');
assert.ok([...generator.springPunchItems.values()].every((item) => item.z === first.z), 'single pickup must not delete the remaining row');
const sibling = [...generator.springPunchItems.values()][0];
const rotationBefore = sibling.mesh.rotation.y;
generator.animateObstacles(.1);
assert.notEqual(sibling.mesh.rotation.y, rotationBefore, 'each box in the horizontal row receives animation updates');
generator.update(0);
const rowsByZ = new Map();
[...generator.springPunchItems.values()].forEach((item) => rowsByZ.set(item.z, [...(rowsByZ.get(item.z) || []), item]));
assert.ok([...rowsByZ.values()].every((items) => new Set(items.map((item) => item.x)).size === items.length), 'all replenished boxes remain horizontal with unique X cells');
const spawnedRows = [...rowsByZ.keys()];
assert.ok(spawnedRows.every((z, index) => spawnedRows.slice(index + 1).every((otherZ) => Math.abs(z - otherZ) >= 3)), 'different party box rows stay at least three Z cells apart');
const row = generator.getActiveRows().get(first.z);
generator.removeRow(first.z, row);
assert.equal([...generator.springPunchItems.values()].some((item) => item.z === first.z), false, 'row cleanup removes every remaining box in that horizontal row');
console.log('spring punch spawn regression: passed');
